### ISSUE TITLE
Cannot use accept plug in pipeline

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#183]
On Saturn 0.8.0, the following code fails:

```fsharp
let myPipe = pipeline {
    plug acceptJson
}

let routes = router {
    pipe_through myPipe
    get "/status" (text "Saturn is awesome!")
}

let app = application {
    url "http://localhost:8080"
    use_router routes
}

run app
```

with the following request:

```http
GET http://localhost:8080/status
content-type: application/json
```

The error given is:

```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8080/status application/json
fail: Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Map[T,TResult](FSharpFunc`2 mapping, IEnumerable`1 source)
   at Giraffe.Core.mustAccept(FSharpList`1 mimeTypes, FSharpFunc`2 next, HttpContext ctx) in C:\projects\giraffe\src\Giraffe\Core.fs:line 518
   at Giraffe.Middleware.Invoke@29.Invoke(Unit unitVar) in C:\projects\giraffe\src\Giraffe\Middleware.fs:line 31
   at FSharp.Control.Tasks.TaskBuilder.run[a](FSharpFunc`2 firstStep) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at Giraffe.Middleware.Invoke@63-5.Invoke(Unit unitVar) in C:\projects\giraffe\src\Giraffe\Middleware.fs:line 63
   at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch) in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 165
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 280.697ms 500 application/json; charset=utf-8
```

I've tried a POST as well with the same error.

**Comment by simax** [comment]
I'm not sure this is a bug. I ran into the same thing but in the end I realised that I needed to add an `Accept` header to my request, not a `content-type` header. If you do that then request works as expected. 

> Accept and Content-type are both headers sent from a client(browser say) to a service. Accept header is a way for a client to specify the media type of the response content it is expecting and Content-type is a way to specify the media type of request being sent from the client to the server

**Comment by ChrSteinert** [comment]
I think this can be closed. 
With Saturn 0.12.1 this no longer throws an error, but returns an expected 404 - the `acceptJson` filters allows requests, that have the `Accept` header set to `application/json`, which also works as expected :)
