### ISSUE TITLE
Template fails when folder is kebab-cased

### ISSUE THREAD

**Issue by draptik** [SaturnFramework/Saturn#282]
I'm having issues getting the default template to run.

Steps to reproduce:

- `dotnet new -i Saturn.Template`
- `mkdir template-demo && cd template-demo`
- `dotnet new saturn -lang f#`
- `dotnet tool restore`
- `dotnet fake build`

IMPORTANT: `template-demo`! The kebab-case (vs snake_case)!

Error:

```sh
$ dotnet fake build       
Extracted Paket.Restore.targets to: /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/.paket/Paket.Restore.targets (Can be disabled with PAKET_SKIP_RESTORE_TARGETS=true)
Starting full restore process.
run Build
Building project with version: LocalBuild
Shortened DependencyGraph for Target Build:
<== Build
   <== Restore
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - Restore
Group - 3
  - Build
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0029261
Starting target 'Restore'
Starting task 'DotNet:restore': /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/src/template_demo/template_demo.fsproj
/home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo> "dotnet"  msbuild /version /nologo (In: false, Out: true, Err: true)
16.5.0.12403
/home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo> "dotnet"  restore /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/src/template_demo/template_demo.fsproj /bl:/tmp/tmpjEqN2D.tmp.binlog (In: false, Out: false, Err: false)
MSBUILD : error MSB1009: Project file does not exist.
Switch: /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/src/template_demo/template_demo.fsproj
msbuild has not created the binlog file as expected, no warnings or errors are reported using native CI capabilities. Use 'DisableInternalBinLog' to 'true' to disable this warning.
Finished (Failed) 'DotNet:restore' in 00:00:00.6752432
Finished (Failed) 'Restore' in 00:00:00.6766986

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target     Duration
------     --------
Clean      00:00:00.0000545
Restore    00:00:00.6766115   (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
Build      00:00:00           (skipped)
Total:     00:00:00.7429543
Status:    Failure
---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Restore' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
Hint: To further diagnose the problem you can run fake in verbose mode `fake -v run ...` or set the 'FAKE_DETAILED_ERRORS' environment variable to 'true'
Hint: Could not find a version in your paket.dependencies file, consider adding 'version 5.241.2' at the top of your dependencies file (/home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/paket.dependencies).
Read https://github.com/fsharp/FAKE/issues/2193 for details.
Hint: The fake-runner has not been updated for at least 6 months. Please consider upgrading to get latest bugfixes, improved suggestions and F# features.
Performance:
 - Cli parsing: 144 milliseconds
 - Packages: 309 milliseconds
   - Creating Runtime Graph: 39 milliseconds
   - Retrieve Assembly List: 340 milliseconds
 - Script compiling: 2 seconds
 - Script analyzing: 108 milliseconds
 - Script running: 849 milliseconds
 - Script cleanup: 35 milliseconds
 - Runtime: 4 seconds
```

Adding the verbose flag `-v` to `fake`:

```sh
# ...
Script reported an error:
-> BuildFailedException: Target 'Restore' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 991
        at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 1173
        at <StartupCode$build_181EF7BB7FD114AB3E616E2D9BE80A08FBAF8FA6E8EC84D1E78E4EC9F2A5B022>.$Build$fsx.main@() in /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/build.fsx:line 47
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
   StackTrace:
        at Fake.DotNet.MSBuild.handleAfterRun(String command, FSharpOption`1 binLogPath, Int32 exitCode, String project) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 756
        at Fake.DotNet.DotNet.restore(FSharpFunc`2 setParams, String project) in D:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 1209
        at Build.clo@15-1.Invoke(TargetParameter _arg1) in /home/patrick/projects/fsharp-saturn-demos/demo1-helloworld/template-demo/build.fsx:line 16
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 300
```

```sh
$ dotnet --info    
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.200/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.108 [/usr/share/dotnet/sdk]
  3.1.200 [/usr/share/dotnet/sdk]
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

```sh
$ dotnet new -l           
...
Templates                                         Short Name               Language          Tags                                                     
------------------------------------------------------------------------------------------------------------------------------------------------------
Console Application                               console                  [C#], F#, VB      Common/Console                                           
Class library                                     classlib                 [C#], F#, VB      Common/Library                                           
WPF Application                                   wpf                      [C#]              Common/WPF                                               
WPF Class library                                 wpflib                   [C#]              Common/WPF                                               
WPF Custom Control Library                        wpfcustomcontrollib      [C#]              Common/WPF                                               
WPF User Control Library                          wpfusercontrollib        [C#]              Common/WPF                                               
Windows Forms (WinForms) Application              winforms                 [C#]              Common/WinForms                                          
Windows Forms (WinForms) Class library            winformslib              [C#]              Common/WinForms                                          
Worker Service                                    worker                   [C#]              Common/Worker/Web                                        
Saturn                                            Saturn                   F#                F#/Web/Framework/ASP.Net/Core/Http/Service/Functional/MVC
Unit Test Project                                 mstest                   [C#], F#, VB      Test/MSTest                                              
NUnit 3 Test Project                              nunit                    [C#], F#, VB      Test/NUnit                                               
NUnit 3 Test Item                                 nunit-test               [C#], F#, VB      Test/NUnit                                               
xUnit Test Project                                xunit                    [C#], F#, VB      Test/xUnit                                               
Razor Component                                   razorcomponent           [C#]              Web/ASP.NET                                              
Razor Page                                        page                     [C#]              Web/ASP.NET                                              
MVC ViewImports                                   viewimports              [C#]              Web/ASP.NET                                              
MVC ViewStart                                     viewstart                [C#]              Web/ASP.NET                                              
Blazor Server App                                 blazorserver             [C#]              Web/Blazor                                               
Blazor WebAssembly App                            blazorwasm               [C#]              Web/Blazor/WebAssembly                                   
ASP.NET Core Empty                                web                      [C#], F#          Web/Empty                                                
ASP.NET Core Web App (Model-View-Controller)      mvc                      [C#], F#          Web/MVC                                                  
ASP.NET Core Web App                              webapp                   [C#]              Web/MVC/Razor Pages                                      
ASP.NET Core with Angular                         angular                  [C#]              Web/MVC/SPA                                              
ASP.NET Core with React.js                        react                    [C#]              Web/MVC/SPA                                              
ASP.NET Core with React.js and Redux              reactredux               [C#]              Web/MVC/SPA                                              
Razor Class Library                               razorclasslib            [C#]              Web/Razor/Library/Razor Class Library                    
ASP.NET Core Web API                              webapi                   [C#], F#          Web/WebAPI                                               
ASP.NET Core gRPC Service                         grpc                     [C#]              Web/gRPC                                                 
dotnet gitignore file                             gitignore                                  Config                                                   
global.json file                                  globaljson                                 Config                                                   
NuGet Config                                      nugetconfig                                Config                                                   
Dotnet local tool manifest file                   tool-manifest                              Config                                                   
Web Config                                        webconfig                                  Config                                                   
Solution File                                     sln                                        Solution                                                 
Protocol Buffer File                              proto                                      Web/gRPC                           
```
I've also tried changing the dotnet version in `global.json` after a fresh install to other versions, but I always get the error from above.

Any pointers? Am I doing something wrong?

**Comment by draptik** [comment]
Ok, after some more experimenting, I was able to find the bug:

When the folder name contains a minus sign, such as `demo-2` the above error happens. If the folder name does not contain a minus sign, everything works.

To reproduce:

```sh
mkdir demo1
mkdir demo-2
```

Other than that, the same procedure as in the original issue:

```sh
dotnet new saturn -lang f#
dotnet tool restore
dotnet fake build
```

In folder `demo1` everything is fine.
In folder `demo-2` I get the error message mentioned above.

I haven't looked at the underlying code, but I'm guessing:
-> typo which lowercases a `-` minus sign to an `_` underscore...

**Comment by draptik** [comment]
Sadly, I haven't found the code where this is evaluated.

**Comment by draptik** [comment]
Oops, and I just noticed that there is a separate github project for Saturn.Template under https://github.com/SaturnFramework/Saturn.Template
My mistake: sorry.

**Comment by draptik** [comment]
duplicate of https://github.com/SaturnFramework/Saturn.Template/issues/9

**Comment by cartermp** [comment]
Will close in favor of https://github.com/SaturnFramework/Saturn.Template/issues/9
