### ISSUE TITLE
Controller DELETE fails with null ref

### ISSUE THREAD

**Issue by isaacabraham** [SaturnFramework/Saturn#44]
This trivial controller fails with the following exception:

```fsharp
let meetingsEndpoint = controller {
    delete (fun (ctx, id) -> (sprintf "Delete meeting %d" id) |> Controller.text ctx) }

let app = application {
    url "http://localhost:8085"
    router meetingsEndpoint }

run app
```

```
Giraffe.Middleware.GiraffeErrorHandlerMiddleware[0]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Saturn.Controller.Yield@48-1.Invoke(Tuple`2 tupledArg) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Controller.fs:line 48
   at Saturn.Controller.controllerWithErrorHandler@149-3.Invoke(Exception _arg2) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Controller.fs:line 152
   at FSharp.Control.Tasks.TaskBuilder.tryWith@168.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Core.chooseHttpFunc@218-1.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@38-5.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Giraffe.Middleware.Invoke@63-8.Invoke(Unit unitVar0)
   at FSharp.Control.Tasks.TaskBuilder.tryWith[a](FSharpFunc`2 step, FSharpFunc`2 catch)
```

May be put this as an up-for-grabs as an opportunity for someone in the community to fix?

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #45
