### ISSUE TITLE
SAFE template application fails to start when diagnostics are enabled

### ISSUE THREAD

**Issue by bartsokol** [SaturnFramework/Saturn#64]
**Steps to reproduce**:
* Create new app using SAFE template with remoting enabled (`dotnet new SAFE -lang F# --remoting`)
* Try to build and start the app (`build run`)

**Actual behaviour**: server side (Saturn) application crashes with following exception:
```
Unhandled Exception: System.ArgumentException: The input sequence was empty.
Parameter name: source
   at Microsoft.FSharp.Collections.SeqModule.Last[T](IEnumerable`1 source)
   at Saturn.SiteMap.generate() in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Diagnostics.fs:line 55
   at Saturn.Application.run(IWebHostBuilder app) in D:\Programowanie\Projekty\Saturn\Saturn\src\Saturn\Application.fs:line 381
   at <StartupCode$Server>.$Server.main@() in C:\work\dotnet\SAFESample\src\Server\Server.fs:line 33
```

It looks like `SiteMap.generate` function is called on empty state. It should be updated with `SiteMap.add` function which seems to be never called.

Disabling diagnostics (using `disable_diagnostics` directive) solves the issue.

Environment: .NET Core SDK 2.1.300, Windows 10, Saturn 0.5

**Comment by Nhowka** [comment]
Maybe using `Seq.tryLast` could be safer with minimal changes.

**Comment by Krzysztof-Cieslak** [comment]
Fixed in https://github.com/SaturnFramework/Saturn/commit/ee03b963fd71414af732b0b1d839002c58257014
